### ISSUE TITLE
foreman plugin does not handle optional ansible_facts

### ISSUE THREAD

**Issue by dekimsey** [theforeman/foreman_ansible#48]
Foreman plugin fails on missing optional facts. 

As of [Ansible 2.1 setup module][0] has a gather_subset flag that can restrict the types of facts to gather.

```
2016-09-16 10:36:39 [app] [I] Import facts for 'port-esb-001.acme.com' completed. Added: 103, Updated: 0, Deleted 0 facts
2016-09-16 10:36:39 [app] [W] Action failed
 | NoMethodError: undefined method `sort' for nil:NilClass
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_ansible-1.0/app/services/foreman_ansible/fact_parser.rb:51:in `get_interfaces'
 | /usr/share/foreman/app/services/fact_parser.rb:61:in `interfaces'
 | /usr/share/foreman/app/models/host/base.rb:207:in `set_interfaces'
 | /usr/share/foreman/app/models/host/base.rb:184:in `populate_fields_from_facts'
 | /usr/share/foreman/app/models/host/managed.rb:468:in `populate_fields_from_facts'
 | /usr/share/foreman/app/models/host/base.rb:158:in `import_facts'
 | /usr/share/foreman/app/controllers/api/v2/hosts_controller.rb:237:in `facts'
```

Environment:

```
katello-3.1.0-5.el7.noarch
foreman-1.12.2-1.el7.noarch
tfm-rubygem-foreman_ansible-1.0-1.fm1_12.el7.noarch
```

[0]: http://docs.ansible.com/ansible/setup_module.html

**Comment by dLobatog** [comment]
On 09/16, Daniel Kimsey wrote:
> Foreman plugin fails on missing optional facts.
>
> As of [Ansible 2.1 setup module][0] has a gather_subset flag that can restrict the types of facts to gather.

Which facts are you getting using gather_subset?
http://docs.ansible.com/ansible/intro_configuration.html#id94 there seem
to be a number of possible options.

Can you provide the JSON that's submitted to Foreman with these facts,
to see how can we replicate the failure too? That'd be really helpful

>
> ```
> 2016-09-16 10:36:39 [app] [I] Import facts for 'port-esb-001.acme.com' completed. Added: 103, Updated: 0, Deleted 0 facts
> 2016-09-16 10:36:39 [app] [W] Action failed
>  | NoMethodError: undefined method `sort' for nil:NilClass
>  | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_ansible-1.0/app/services/foreman_ansible/fact_parser.rb:51:in `get_interfaces'
>  | /usr/share/foreman/app/services/fact_parser.rb:61:in `interfaces'
>  | /usr/share/foreman/app/models/host/base.rb:207:in `set_interfaces'
>  | /usr/share/foreman/app/models/host/base.rb:184:in `populate_fields_from_facts'
>  | /usr/share/foreman/app/models/host/managed.rb:468:in `populate_fields_from_facts'
>  | /usr/share/foreman/app/models/host/base.rb:158:in `import_facts'
>  | /usr/share/foreman/app/controllers/api/v2/hosts_controller.rb:237:in `facts'
> ```
>
> Environment:
>
> ```
> katello-3.1.0-5.el7.noarch
> foreman-1.12.2-1.el7.noarch
> tfm-rubygem-foreman_ansible-1.0-1.fm1_12.el7.noarch
> ```
>
> [0]: http://docs.ansible.com/ansible/setup_module.html

Thanks for the report!


>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/theforeman/foreman_ansible/issues/48

--
Daniel Lobato Garcia

@dLobatog
blog.daniellobato.me
daniellobato.me

GPG: http://keys.gnupg.net/pks/lookup?op=get&search=0x7A92D6DD38D6DE30
Keybase: https://keybase.io/elobato
