### ISSUE TITLE
Runner error: RuntimeError - can't get Master/Slave device

### ISSUE THREAD

**Issue by mtkh** [theforeman/foreman_ansible#52]
![foreman ansible](https://cloud.githubusercontent.com/assets/16597922/19243093/6ff060ac-8f16-11e6-857f-de65e4324a33.png)

Any solution please?

**Comment by dLobatog** [comment]
@iNecas does this sound familiar? This looks like a problem when running Ansible itself not with foreman_ansible or the proxy but it might be something in dynflow I'm not aware of.

**Comment by bndabbs** [comment]
I am seeing the same issue running `foreman-1.13.0-1.el7.noarch` with `katello-3.2.0-2.rc1.el7.noarch`.

Here is the relevant log output:
```
2016-10-18 16:04:33 7b431b26 [app] [I] Redirected to https://REDACTED/foreman_tasks/tasks/239ca060-c47a-4e82-b222-c337e492cf4d
2016-10-18 16:04:33 7b431b26 [app] [I] Completed 302 Found in 156ms (ActiveRecord: 23.7ms)
2016-10-18 16:04:33 7b431b26 [app] [I] Started GET "/foreman_tasks/tasks/239ca060-c47a-4e82-b222-c337e492cf4d" for REDACTED at 2016-10-18 16:04:33 -0400
2016-10-18 16:04:33 7b431b26 [app] [I] Processing by ForemanTasks::TasksController#show as HTML
2016-10-18 16:04:33 7b431b26 [app] [I]   Parameters: {"id"=>"239ca060-c47a-4e82-b222-c337e492cf4d"}
2016-10-18 16:04:33 7b431b26 [app] [I]   Rendered /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-0.8.2/app/views/foreman_tasks/tasks/_details.html.erb (24.9ms)
2016-10-18 16:04:33 7b431b26 [app] [I]   Rendered /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-0.8.2/app/views/foreman_tasks/tasks/_running_steps.html.erb (0.2ms)
2016-10-18 16:04:33 7b431b26 [app] [I]   Rendered /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-0.8.2/app/views/foreman_tasks/tasks/_errors.html.erb (0.2ms)
2016-10-18 16:04:33 7b431b26 [app] [I]   Rendered /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-0.8.2/app/views/foreman_tasks/tasks/_raw.html.erb (2.4ms)
2016-10-18 16:04:33 7b431b26 [app] [I]   Rendered /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-0.8.2/app/views/foreman_tasks/tasks/_locks.html.erb (1.0ms)
2016-10-18 16:04:33 7b431b26 [app] [I]   Rendered /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-0.8.2/app/views/foreman_tasks/tasks/show.html.erb within layouts/application (30.7ms)
2016-10-18 16:04:33 7b431b26 [app] [I]   Rendered layouts/_application_content.html.erb (0.3ms)
2016-10-18 16:04:33 7b431b26 [app] [I]   Rendered home/_user_dropdown.html.erb (1.8ms)
2016-10-18 16:04:33 7b431b26 [app] [I] Read fragment views/tabs_and_title_records-4 (0.1ms)
2016-10-18 16:04:33 7b431b26 [app] [I]   Rendered home/_topbar.html.erb (7.1ms)
2016-10-18 16:04:33 7b431b26 [app] [I]   Rendered layouts/base.html.erb (8.6ms)
2016-10-18 16:04:33 7b431b26 [app] [I] Completed 200 OK in 48ms (Views: 39.6ms | ActiveRecord: 2.1ms)
2016-10-18 16:04:34  [foreman-tasks/dynflow] [E] error while dispatching request to runner c050596c-041a-4e0b-8843-678cd1812e1e:RuntimeError can't get Master/Slave device:
 |  /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-core-0.1.1/lib/foreman_tasks_core/runner/command_runner.rb:8:in `spawn'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-core-0.1.1/lib/foreman_tasks_core/runner/command_runner.rb:8:in `initialize_command'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_ansible_core-0.0.1/lib/foreman_ansible_core/playbook_runner.rb:21:in `block in start'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_ansible_core-0.0.1/lib/foreman_ansible_core/playbook_runner.rb:20:in `chdir'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_ansible_core-0.0.1/lib/foreman_ansible_core/playbook_runner.rb:20:in `start'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-core-0.1.1/lib/foreman_tasks_core/runner/dispatcher.rb:29:in `start_runner'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.15/lib/dynflow/actor.rb:6:in `on_message'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/context.rb:46:in `on_envelope'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-core-0.1.1/lib/foreman_tasks_core/runner/dispatcher.rb:22:in `on_envelope'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/executes_context.rb:7:in `on_envelope'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.15/lib/dynflow/actor.rb:26:in `on_envelope'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/awaits.rb:15:in `on_envelope'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/sets_results.rb:14:in `on_envelope'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/buffer.rb:38:in `process_envelope'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/buffer.rb:31:in `process_envelopes?'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/buffer.rb:20:in `on_envelope'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/termination.rb:55:in `on_envelope'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/removes_child.rb:10:in `on_envelope'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/behaviour/sets_results.rb:14:in `on_envelope'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/core.rb:161:in `process_envelope'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/core.rb:95:in `block in on_envelope'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/core.rb:118:in `block (2 levels) in schedule_execution'
 | /opt/rh/sclo-ror42/root/usr/share/gems/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
 | /opt/rh/sclo-ror42/root/usr/share/gems/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
 | /opt/rh/sclo-ror42/root/usr/share/gems/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/concurrent-ruby-edge-0.2.0/lib/concurrent/actor/core.rb:115:in `block in schedule_execution'
 | /opt/rh/sclo-ror42/root/usr/share/gems/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/serialized_execution.rb:18:in `call'
 | /opt/rh/sclo-ror42/root/usr/share/gems/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/serialized_execution.rb:18:in `call'
 | /opt/rh/sclo-ror42/root/usr/share/gems/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/serialized_execution.rb:96:in `work'
 | /opt/rh/sclo-ror42/root/usr/share/gems/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/serialized_execution.rb:77:in `block in call_job'
 | /opt/rh/sclo-ror42/root/usr/share/gems/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:333:in `call'
 | /opt/rh/sclo-ror42/root/usr/share/gems/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:333:in `run_task'
 | /opt/rh/sclo-ror42/root/usr/share/gems/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:322:in `block (3 levels) in create_worker'
 | /opt/rh/sclo-ror42/root/usr/share/gems/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:305:in `loop'
 | /opt/rh/sclo-ror42/root/usr/share/gems/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:305:in `block (2 levels) in create_worker'
 | /opt/rh/sclo-ror42/root/usr/share/gems/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:304:in `catch'
 | /opt/rh/sclo-ror42/root/usr/share/gems/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:304:in `block in create_worker'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2016-10-18 16:04:34  [foreman-tasks/action] [E] Script execution failed
```

**Comment by iNecas** [comment]
Seem like some issue with spawning a PTY console for running the `ansible-playbook`. Please try 

```ruby
ruby -rpty  -e 'puts PTY.spawn("ls hello");'
```

One candidate that I would have is selinux preventing this. Could you try `setenforce 0` temporarily  to see if it helps with the problem?

**Comment by bndabbs** [comment]
Ivan, thanks for the pointer. I have it working now with the following fixes:

1. 
   SELinux was preventing the console, as you had indicated:
   ```
sudo audit2allow -al


#============= passenger_t ==============

#!!!! This avc can be allowed using the boolean 'daemons_use_tty'
allow passenger_t devpts_t:chr_file open;
allow passenger_t devpts_t:filesystem getattr;
allow passenger_t ldconfig_exec_t:file { read execute open execute_no_trans };
allow passenger_t ptmx_t:chr_file { ioctl open getattr };
allow passenger_t tmpfs_t:dir { write remove_name add_name };
allow passenger_t tmpfs_t:file { write getattr link read create unlink open };
allow passenger_t tmpfs_t:filesystem getattr;
allow passenger_t user_home_t:file { read open };
allow passenger_t usr_t:dir { write remove_name create rmdir add_name };
allow passenger_t usr_t:file { write rename create unlink };
```
   This was fixed by running the following commands: 
   `sudo audit2allow -al -t passenger_t -M passenger_tty`
   `sudo semodule -i passenger_tty.pp`
2. After fixing `#1`, I was getting a filesystem permission error:

   ```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 44, in <module>
    import ansible.constants as C
  File "/usr/lib/python2.7/site-packages/ansible/constants.py", line 152, in <module>
    DEFAULT_LOCAL_TMP         = get_config(p, DEFAULTS, 'local_tmp',        'ANSIBLE_LOCAL_TEMP',      '$HOME/.ansible/tmp', istmppath=True)
  File "/usr/lib/python2.7/site-packages/ansible/constants.py", line 78, in get_config
    os.makedirs(value, 0o700)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/share/foreman/.ansible'
```

   This was fixed with: `sudo chown foreman.foreman /usr/share/foreman`

   I am still working around an issue with host key validation causing the playbook to pause indefinitely, but that is outside the scope of this issue.
